/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle_learn;
import com.gradle.CustomLib;

public class App {
    public String getGreeting() {
        return "Hello World!" + CustomLib.identifier;
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
